name: Test Backend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          version: "2.1.3"
          enable-cache: true

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run pytests
        run: poetry run pytest
        working-directory: api/app
